### ISSUE TITLE
v1.0 Metaissue

### ISSUE THREAD

**Issue by zslayton** [zslayton/cron#67]
Items in this list need to be completed before 1.0 is cut, but they will be released incrementally in minor version bumps.

TODO:

- [ ] `PartialEq` and `Eq` implementations for `Schedule` (See #61)
- [ ] Allow users to test whether a given `DateTime` matches their schedule (See #16)
- [ ] Allow users to iterate over a `Schedule` backwards, viewing matching historical `DateTime`s (See #66)
- [ ] Provide a convenience method for iterating over a window of time (`schedule.from(time1).to(time2)`)
- [ ] `ScheduleParserBuilder` that allows users to specify different configuration options. Options included TBD, but ideas include:
  - 0- vs 1-based indexing for some fields
  - Recognizing a different set of strings for days of the week or months of the year
  - Specifying whether an extra field represents seconds or years (See #13)
  
  No individual option is required for 1.0, but introducing a `ScheduleParserBuilder` is. Individual options can be added without it being a breaking change.
- [ ] Proper documentation
- [ ] Re-license to dual MIT/Apache2

**Comment by Stupremee** [comment]
I suggest to add a high level `parse` method so you can parse a cron expression using something like this:

```rust
let job = cron::parse(some_cron_expr).unwrap();

// ...
```

This feels much more natural and is easier to read.

**Comment by willbuckner** [comment]
Would it be possible to do even a beta or RC release sometime soon? :) The `nom` update is needed to fix an incompatibility with argonautica v2:

Running `cargo outdated` gives me this, and I know some others around the internet are reporting the same.

Happy to help test an RC and provide feedback!

```
error: failed to select a version for `nom`.
    ... required by package `argonautica v0.2.0`
    ... which satisfies dependency `argonautica = "^0.2.0"` of package `<my crate> v0.1.0 (/var/folders/4n/dw119dzd09xg6g65gc2zv1qc0000gp/T/cargo-outdatedFGZAad)`
versions that meet the requirements `^4.2` are: 4.2.3, 4.2.2, 4.2.1, 4.2.0

all possible versions conflict with previously selected packages.

  previously selected package `nom v4.1.0`
    ... which satisfies dependency `nom = "~4.1"` of package `cron v0.9.0`
    ... which satisfies dependency `cron = "^0.9.0"` of package `<my crate> v0.1.0 (/var/folders/4n/dw119dzd09xg6g65gc2zv1qc0000gp/T/cargo-outdatedFGZAad)`

failed to select a version for `nom` which could resolve this conflict
```

**Comment by zslayton** [comment]
Hi @willbuckner, no need to wait on the full `v1.0`, I'll try to get a `v0.10` with the latest commits published soon.

**Comment by willbuckner** [comment]
Thanks so much!
